#pragma config(Motor,  port2,           driveLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armClaw,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armBox,        tmotorVex393_MC29, openLoop)

//Vex 2017-2018 in the zone autonomous.

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

/*---------------------------------------------------------------------------*/
/*                                                                           */
/* Desc: VEX 42627G Team Digital Minds Copyright(with help from 315 Paradigm)*/
/*                    						Credit:																		 */
/*                    Head Developers: Mukul Rao, Jeffrey Tu				         */
/*                    																	                     */
/*                    						Assistant: Mihir                           */
/*                                                                           */
/*                                                                           */
/*       Filter Function/Move filter credit: Kaushik from 315 Paradigm       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task openClaw(){
		motor[armClaw] = -40;
		wait1Msec(750);
		motor[armClaw] = 0;
}

task boxUpAuton(){
	motor[armBox] = 80;
}

task armUp(){
	motor[leftArm] = 80;
	motor[rightArm] = -80;
}

task boxDownAuton(){
	motor[armBox] = -80;
}

task armDown(){
	motor[leftArm] = -80;
	motor[rightArm] = 80;
}

task moveForwardAuton(){
	motor[driveLeft] = 80;
	motor[driveRight] = -80;
}

task moveBackwardAuton(){
	motor[driveLeft] = -80;
	motor[driveRight] = 80;
}


task turnRightAuton(){
	motor[driveRight] = 80;
	motor[driveLeft] = 80;

}

task turnLeftAuton(){
	motor[driveRight] = -80;
	motor[driveLeft] = -80;
}

task stopAllMotorsAuton(){
	motor[driveRight] = 0;
	motor[driveLeft] = 0;
	motor[armBox] = 0;
	motor[armClaw] = 0;
	motor[leftArm] = 0;
	motor[mogo] = 0;
	motor[rightArm] = 0;
}

task mogoDownAuton(){
	motor[mogo] = -80;
	wait1Msec(1250);
	stopMotor(mogo);
}

task mogoUpAuton(){
	motor[mogo] = 80;
	wait1Msec(1250);
	stopMotor(mogo);
}

task autonomous(){
	// NEGATIVE MOVES FORWARD ON RIGHT SIDE FOR DRIVETRAIN!!!!!
	//NEGATIVE MOVES BACKWARD ON THE LEFT SIDE FOR DRIVETRAIN!!!!!!

	startTask(armUp);
	wait1Msec(500);
	startTask(mogoDownAuton);
	startTask(moveForwardAuton);
	wait1Msec(2000);
	startTask(stopAllMotorsAuton);

	//-----------------

	startTask(mogoUpAuton);
	wait1Msec(500);
	startTask(armDown);
	wait1Msec(1000);
	startTask(stopAllMotorsAuton);
	startTask(openClaw);
	startTask(armUp);
	wait1Msec(250);
	startTask(stopAllMotorsAuton);

	/* EXTRA AUTONS! DO NOT USE!

	/*



	startTask(moveBackwardAuton);
	wait1Msec(1500);
	startTask(stopAllMotorsAuton);

	//-----------------

	startTask(turnRightAuton);
	wait1Msec(1200);
	startTask(stopAllMotorsAuton);

	//-----------------

	startTask(moveForwardAuton);
	wait1Msec(1500);
	startTask(stopAllMotorsAuton);

	//-----------------

	startTask(mogoDownAuton);








	startTask(boxDownAuton);
	wait1Msec(250);
	startTask(stopAllMotorsAuton);

	startTask(armUp);
	wait1Msec(500);
	startTask(stopAllMotorsAuton);

	startTask(mogoDownAuton);
	startTask(moveForwardAuton);
	wait1Msec(1750);
	startTask(stopAllMotorsAuton);

	startTask(mogoUpAuton);
	startTask(boxUpAuton);
	wait1Msec(250);
	startTask(stopAllMotorsAuton);
	startTask(armDown);
	wait1Msec(500);
	startTask(openClaw);
	startTask(stopAllMotorsAuton);
	startTask(mogoDownAuton);
	startTask(moveBackwardAuton);
	wait1Msec(1000);
	startTask(stopAllMotorsAuton);


	startTask(armUp);
	wait1Msec(2000);
	startTask(stopAllMotorsAuton);
	startTask(moveForwardAuton);
	wait1Msec(1000);
	startTask(stopAllMotorsAuton);
	startTask(armDown);
	wait1Msec(250);
	startTask(stopAllMotorsAuton);
	startTask(openClaw);
	startTask(stopAllMotorsAuton);
	*/

	startTask(moveBackwardAuton);
	wait1Msec(1500);
	startTask(stopAllMotorsAuton);

	//-----------------

	startTask(turnRightAuton);
	wait1Msec(1200);
	startTask(stopAllMotorsAuton);

	//-----------------

	startTask(moveForwardAuton);
	wait1Msec(1500);
	startTask(stopAllMotorsAuton);

	//-----------------

	startTask(mogoDownAuton);








	startTask(boxDownAuton);
	wait1Msec(250);
	startTask(stopAllMotorsAuton);

	startTask(armUp);
	wait1Msec(500);
	startTask(stopAllMotorsAuton);

	startTask(mogoDownAuton);
	startTask(moveForwardAuton);
	wait1Msec(1750);
	startTask(stopAllMotorsAuton);

	startTask(mogoUpAuton);
	startTask(boxUpAuton);
	wait1Msec(250);
	startTask(stopAllMotorsAuton);
	startTask(armDown);
	wait1Msec(500);
	startTask(openClaw);
	startTask(stopAllMotorsAuton);
	startTask(mogoDownAuton);
	startTask(moveBackwardAuton);
	wait1Msec(1000);
	startTask(stopAllMotorsAuton);


	startTask(armUp);
	wait1Msec(2000);
	startTask(stopAllMotorsAuton);
	startTask(moveForwardAuton);
	wait1Msec(1000);
	startTask(stopAllMotorsAuton);
	startTask(armDown);
	wait1Msec(250);
	startTask(stopAllMotorsAuton);
	startTask(openClaw);
	startTask(stopAllMotorsAuton);
	*/
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task i s used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                    User Control Drivetrain functions                      */
/*                                                                           */
/*   All functions for drive train for [Digitron]Team 42627G Digital Minds   */
/*                                                                           */
/*                                                                           */
/*                                                                           */
/*---------------------------------------------------------------------------*/



/*------------------Dead zone filter------------------------*/
int filter(int input){
	if (input > 20 || input < -20){
		return input;
	}
	else {
		return 0;
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

/*------------------------Drive-----------------------------*/
task drive(){
	while (true){
		//forward backward
		int forward = filter(vexRT[Ch1]);
		//turning
		int turn = filter(vexRT[Ch3]);

		motor[driveRight] = forward - turn;
		motor[driveLeft] = forward + turn;
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

/*------------------Mobile Goal-----------------------------*/
task mogoLift() {
	while(true){
		//assigning lifting the mobile goal to the upper 8-pad button
		while(vexRT[Btn8U] == 1){
			startMotor(mogo, 80);
		}
		stopMotor(mogo);
		//assigning dropping the mobile goal to the bottom 8-pad button
		while(vexRT[Btn8D] == 1){
			startMotor(mogo, -80);
		}
		stopMotor(mogo);
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/



/*------------------Arm and claw and boxlift-----------------------------*/

task arm() {
	while(true){
		//assigning lifting the arm to the upper 6-button pad.
		while(vexRT[Btn6U] == 1) {
			startMotor(leftArm, 80);
			startMotor(rightArm, -80);
		}
		stopMotor(leftArm);
		stopMotor(rightArm);
		//assigning dropping the arm to the bottom 6-buttom pad.
		while(vexRT[Btn6D] == 1){
			startMotor(leftArm, -80);
			startMotor(rightArm, 80);
		}
		stopMotor(leftArm);
		stopMotor(rightArm);
	}
}

task box() {
	while(true){
		//box
		while(vexRT[Btn5U] == 1){
			startMotor(armBox, -80);
		}
		stopMotor(armBox);

		//box
		while(vexRT[Btn5D] == 1){
			startMotor(armBox, 80);
		}
		stopMotor(armBox);
	}
}

task claw() {
	while(true){
		//claw open
		while(vexRT[Btn8R] == 1){
			startMotor(armClaw, -40);
		}
		stopMotor(armClaw);
		// claw close
		while(vexRT[Btn8L] == 1){
			startMotor(armClaw, 30);
		}
		stopMotor(armClaw);
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

//This task drives everything.
task usercontrol()
{
	startTask(drive);
	startTask(mogoLift);
	startTask(arm);
	startTask(box);
	startTask(claw);
}
