#pragma config(Motor,  port1,           driveTopLeft,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveBottomLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveTopRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveBottomRight, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){ //keeping the controls running all throughout the match
		//Drive forward/backward motors
		motor[driveTopLeft] = vexRT[Ch3];
		motor[driveBottomLeft] = vexRT[Ch3];
		motor[driveTopRight] = vexRT[Ch3];
		motor[driveBottomRight] = vexRT[Ch3];

		//point turns right

		if(vexRT[Ch1] > 0){
			motor[driveTopLeft] = 95;
			motor[driveBottomLeft] = 95;
			motor[driveTopRight] = -95;
			motor[driveBottomRight] = -95;
		}

		//point turns left

		if(vexRT[Ch1] < 0){
			motor[driveTopLeft] = -95;
			motor[driveBottomLeft] = -95;
			motor[driveTopRight] = 95;
			motor[driveBottomRight] = 95;
		}



	}
}
