#pragma config(Motor,  port2,           driveLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armClaw,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armBox,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void boxForward(int power){
	motor[armBox] = 1 * power;
}

void boxBackward(int power){
	motor[armBox] = -1 * power;
}

void openClaw(int power){
	motor[armClaw] = -1 * power;
	wait1Msec(400);
	motor[armClaw] = 0;
}

void closeClaw(int power){
	motor[armClaw] = power;
}

void armUp(int power){
	motor[leftArm] = power;
	motor[rightArm] = -1 * power;
}

void armDown(int power){
	motor[leftArm] = -1 * power;
	motor[rightArm] = power;
}

void moveForwardAuton(int power, int time){
	motor[driveLeft] = power;
	motor[driveRight] = power;
	wait1Msec(time);
	motor[driveLeft] = -25;
	motor[driveRight] = -25;
	wait1Msec(100);
	motor[driveLeft] = 0;
	motor[driveRight] = 0;
}

void moveBackwardAuton(int power, int time){
	motor[driveLeft] = -power;
	motor[driveRight] = -power;
	wait1Msec(time);
	motor[driveLeft] = -25;
	motor[driveRight] = -25;
	wait1Msec(100);
	motor[driveLeft] = 0;
	motor[driveRight] = 0;
}

void turnRightAuton(int power){
	motor[driveRight] = -power;
	motor[driveLeft] = power;
}

void turnLeftAuton(int power){
	motor[driveRight] = power;
	motor[driveLeft] = -power;
}

void stopAllMotorsAuton(){
	motor[driveRight] = 0;
	motor[driveLeft] = 0;
	motor[armBox] = 0;
	motor[armClaw] = 0;
	motor[leftArm] = 0;
	motor[mogo] = 0;
	motor[rightArm] = 0;
}

void mogoDownAuton(){
	motor[mogo] = -127;
	wait1Msec(1250);
	motor[mogo] = 0;
}

void mogoUpAuton(){
	motor[mogo] = 127;
	wait1Msec(1250);
	motor[mogo] = 0;
}

void staticGoal(){
	//arm up
	armUp(50);
	wait1Msec(1600);
	stopAllMotorsAuton();
	//mogoDownAuton();
	//move forward
	moveForwardAuton(80, 625);
	boxForward(127);
	wait1Msec(200);
	stopAllMotorsAuton();
	// waiting to stop cone from shaking
	wait1Msec(500);
	openClaw(80);
	moveBackwardAuton(80, 500);
	boxBackward(127);
	wait1Msec(600);
	stopAllMotorsAuton();
}

void Left_OR_Right_Auton(bool left){
	// Close the claw so that cone doesn't fall off.
	closeClaw(40);
	// Lift arm
	// Bring the mogo down
	// Move forward to the mobile goal
	armUp(50);
	wait1Msec(250);
	motor[mogo] = -127;
	// mogoDown waits, no need to add additional wait here
	moveForwardAuton(127, 1675);
	motor[mogo] = 0;
	// Pickup mobile goal
	// Drop the yellow cone on mobile goal
	mogoUpAuton();
	// mogoUp waits, no need to add additional wait here
	armDown(80);
	wait1Msec(750);
	stopAllMotorsAuton();
	// Place the yellow cone on the mobile goal
	openClaw(40);
	stopAllMotorsAuton();

	// Come back straight
	moveBackwardAuton(127, 1200);

	if (left) {
		turnRightAuton(80);
		} else {
		turnLeftAuton(80);
	}

	wait1Msec(650);
	stopAllMotorsAuton();
	armDown(80);
	wait1Msec(100);

	// Align the back against the fence
	moveBackwardAuton(80, 600);
	// Move forward so that there is enough clearence from the fence
	// to turn.
	moveForwardAuton(80, 225);
	if (left) {
		turnRightAuton(80);
		} else {
		turnLeftAuton(80);
	}
	wait1Msec(450);
	stopAllMotorsAuton();

	moveForwardAuton(127, 950);

	// Now turn either right or left so that the robot
	// faces the drop zone.
	if (left) {
		turnRightAuton(80);
		} else {
		turnLeftAuton(80);
	}
	wait1Msec(650);
	stopAllMotorsAuton();
	// Lift the arm up
	// Move forward so that robot's front is well within 10 point zone
	// Drop the mobile goal in 20 point zone
	// Drive back a bit
	armUp(80);
	wait1Msec(400);
	stopAllMotorsAuton();
	moveForwardAuton(127, 1250);
	mogoDownAuton();
	moveBackwardAuton(127, 150);
	mogoUpAuton();
	armDown(80);
	wait1Msec(50);
	stopAllMotorsAuton();
	moveBackwardAuton(127, 250);
}

task main(){
	while(vexRT[Btn7R] != 1){
	}
	staticGoal();
}
