#pragma config(Motor,  port2,           driveRightFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveRightBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveLeftFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveLeftBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mogo,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*  Desc: VEX 42627G Team Digital Minds Copyright(with help from 315 Paradigm)  */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                    User Control Drivetrain functions                      */
/*                                                                           */
/*   All functions for drive train for [Digitron]Team 42627G Digital Minds   */
/*                                                                           */
/*                                                                           */
/*                                                                           */
/*---------------------------------------------------------------------------*/



/*------------------Dead zone filter------------------------*/
int filter(int input){
	if (input > 20 || input < -20){
		return input;
	}
	else {
		return 0;
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

/*------------------------Drive-----------------------------*/
task drive(){
	while (true){
		//forward backward
		int forward = filter(vexRT[Ch1] + vexRT[Ch3Xmtr2]);
		//turning
		int turn = filter(vexRT[Ch3] + vexRT[Ch1Xmtr2]);

		motor[driveLeftFront] = forward + turn;
		motor[driveLeftBack] = forward + turn;
		motor[driveRightFront] = forward - turn;
		motor[driveRightBack] = forward - turn;
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/




/*------------------Mobile Goal-----------------------------*/
task mogoLift() {
	while(true){
		//assigning lifting the mobile goal to the upper 8-pad button
		while(vexRT[Btn8U] == 1){
			startMotor(port6, 80);
		}
		stopMotor(port6);
		//assigning dropping the mobile goal to the bottom 8-pad button
		while(vexRT[Btn8D] == 1){
			startMotor(port6, -80);
		}
		stopMotor(port6);
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/


task usercontrol()
{
	/*motor[mogo] = -127;
	wait1Msec(1000);
	motor[mogo] = 0;
	*/
	startTask(drive);
	startTask(mogoLift);
}
