#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftMotors,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Vex EDR team Digital Minds Copyright                                                         */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                    User Control Drivetrain functions                      */
/*                                                                           */
/*   All functions for drive train for [Digitron]Team 42627G Digital Minds   */
/*                                                                           */
/*                                                                           */
/*                                                                           */
/*---------------------------------------------------------------------------*/




void forwardAndBackward(){
	/*
	if vexRT[Ch3] > 0 && vexRT[Ch3] < 15 then set
	*/
	startMotor(leftMotor, vexRT[Ch3]);
	startMotor(rightMotor, vexRT[Ch3]);
}

void rightPointTurns(){
	/*
	if vexRT[Ch3] > 0 && vexRT[Ch3] < 15 then set
	*/
	if(vexRT[Ch1] > 0){
		startMotor(leftMotor, 95);
		startMotor(rightMotor, -95);
		//motor[port2] = 95;
		//motor[port3] = -95;
	}
}

void leftPointTurns(){
	/*
	if vexRT[Ch3] > 0 && vexRT[Ch3] < 15 then set
	*/
	if(vexRT[Ch1] < 0){
		startMotor(leftMotor, 95);
		startMotor(rightMotor, -95);
		//motor[port2] = -95;
		//motor[port3] = 95;
	}
}

void liftMobileGoal() {
	/*
	if vexRT[Ch3] > 0 && vexRT[Ch3] < 15 then set
	*/
	if(vexRT[Btn8U] == 1){
		startMotor(liftMotors, 30);
		wait1Msec(750);
		stopMotor(liftMotors);
	}
}

void dropMobileGoal() {
	/*
	if vexRT[Ch3] > 0 && vexRT[Ch3] < 15 then set
	*/
	if(vexRT[Btn8D] == 1){
		startMotor(liftMotors, -30);
		wait1Msec(750);
		stopMotor(liftMotors);
	}
}

task usercontrol()
{
	// User control code here, inside the loop

	while (true){
		// Drive forward/backward motors
		forwardAndBackward();
		// point turns right
		rightPointTurns();
		// point turns left
		leftPointTurns();
		// lift mobile goal
		liftMobileGoal();
		// drop mobile goal
		dropMobileGoal();
	}
}
