#pragma config(Motor,  port2,           driveLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveRight,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armClaw,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armBox,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*               Desc: VEX 42627G Team Digital Minds Copyright               */
/*                    						Credit:																		 */
/*                    Head Developers: Mukul Rao, Jeffrey Tu				         */
/*                                    									                     */
/*                    				                                               */
/*                                                                           */
/*                                                                           */
/*     Filter Function/deadzone filter credit: Kaushik from 315 Paradigm,    */
/*                        as well as some other ideas.                       */
/*---------------------------------------------------------------------------*/

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

const short rightButton = 4;
const short centerButton = 2;

//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(true){
		if(nLCDButtons == rightButton || nLCDButtons == centerButton) {
			break;
		}
	}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

int autonomousOption = -1;



/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void pre_auton(){
	// Enable LCD Display.
	bLCDBacklight = true;
	int currentOption = 0;

	//clearing existing LCD text
	clearLCDLine(0);
	clearLCDLine(1);

	bool optionSelected = false;
	while(!optionSelected){
		switch(currentOption){
		case 0:
			displayLCDCenteredString(0, "RedL mobile");
			displayLCDCenteredString(1, "Enter ==>");
			waitForPress();
			if(nLCDButtons == centerButton){
				waitForRelease();
				optionSelected = true;
				autonomousOption = 0;
				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDCenteredString(0, "RedL mobile");
			} else if(nLCDButtons == rightButton){
				waitForRelease();
				currentOption++;
			}
			break;
		case 1:
			displayLCDCenteredString(0, "BlueR mobile");
			displayLCDCenteredString(1, "Enter ==>");
			waitForPress();
			if(nLCDButtons == centerButton){
				waitForRelease();
				optionSelected = true;
				autonomousOption = 1;
				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDCenteredString(0, "BlueR mobile");
			} else if(nLCDButtons == rightButton){
				waitForRelease();
				currentOption++;
			}
			break;
		case 2:
			displayLCDCenteredString(0, "Static Goal");
			displayLCDCenteredString(1, "Enter ==>");
			waitForPress();
			if(nLCDButtons == centerButton){
				waitForRelease();
				optionSelected = true;
				autonomousOption = 2;
				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDCenteredString(0, "Static Goal");
			} else if(nLCDButtons == rightButton){
				waitForRelease();
				currentOption++;
			}
			break;
		case 3:
			displayLCDCenteredString(0, "Disable Auton");
			displayLCDCenteredString(1, "Enter ==>");
			waitForPress();
			if(nLCDButtons == centerButton){
				waitForRelease();
				optionSelected = true;
				autonomousOption = 3;
				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDCenteredString(0, "Disabled");
			} else if(nLCDButtons == rightButton){
				waitForRelease();
				currentOption = 0;
			}
			break;
		}
	}

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void boxForward(int power){
		motor[armBox] = 1 * power;
}

void openClaw(int power){
	motor[armClaw] = -1 * power;
	//wait1Msec(750);
	wait1Msec(400);
	motor[armClaw] = 0;
}

void armUp(int power){
	motor[leftArm] = power;
	motor[rightArm] = -1 * power;
}

void armDown(int power){
	motor[leftArm] = -1 * power;
	motor[rightArm] = power;
}

void moveForwardAuton(int power){
	motor[driveLeft] = power;
	motor[driveRight] = -1 * power;
}

void moveBackwardAuton(int power){
	motor[driveLeft] = -1 * power;
	motor[driveRight] = power;
}

void turnRightAuton(int power){
	motor[driveRight] = power;
	motor[driveLeft] = power;
}

void turnLeftAuton(int power){
	motor[driveRight] = -1 * power;
	motor[driveLeft] = -1 * power;
}

void stopAllMotorsAuton(){
	motor[driveRight] = 0;
	motor[driveLeft] = 0;
	motor[armBox] = 0;
	motor[armClaw] = 0;
	motor[leftArm] = 0;
	motor[mogo] = 0;
	motor[rightArm] = 0;
}

void mogoDownAuton(){
	motor[mogo] = -127;
	wait1Msec(1200);
	motor[mogo] = 0;
}

void mogoUpAuton(){
	motor[mogo] = 127;
	wait1Msec(1200);
	motor[mogo] = 0;
}

void RL_OR_BR_MobileAuton(bool redLeft){
	// Lift arm
	// Bring the mogo down
	// Move forward to the mobile goal
	armUp(50);
	wait1Msec(250);
	mogoDownAuton();
	// mogoDown waits, no need to add additional wait here
	moveForwardAuton(127);
	wait1Msec(1600);
	stopAllMotorsAuton();

	// Pickup mobile goal
	// Drop the yellow cone on mobile goal
	mogoUpAuton();
	// mogoUp waits, no need to add additional wait here
	armDown(80);
	wait1Msec(1000);
	stopAllMotorsAuton();
	openClaw(40);
	armUp(80);
	wait1Msec(250);
	stopAllMotorsAuton();

	// If we are pursuing red left auton then the robot
	// has to turn left slightly otherwise if we are pursuing
	// blue right auton then the robot has to turn right slightly.
	if (redLeft) {
		turnLeftAuton(80);
	} else {
		turnRightAuton(80);
	}
	wait1Msec(100);
	stopAllMotorsAuton();

	//continue normal routine
	moveBackwardAuton(127);
	wait1Msec(2275);
	stopAllMotorsAuton();

	// Depending on whether we are pursuing red left or blue right
	// we have to either turn left or turn right so that the robot
	// can be facing the drop zone.
	if (redLeft) {
		turnLeftAuton(80);
	} else {
		turnRightAuton(80);
	}
	wait1Msec(900);
	stopAllMotorsAuton();

	// Lift the arm up
	// Move forward so that robot's front is well within 10 point zone
	// Drop the mobile goal in 20 point zone
	// Drive back a bit
	armUp(80);
	wait1Msec(400);
	stopAllMotorsAuton();
	moveForwardAuton(127);
	wait1Msec(1500);
	stopAllMotorsAuton();
	mogoDownAuton();
	moveBackwardAuton(127);
	wait1Msec(150);
	stopAllMotorsAuton();
	mogoUpAuton();
	armDown(80);
	wait1Msec(600);
	stopAllMotorsAuton();
	moveBackwardAuton(127);
	wait1Msec(750);
	stopAllMotorsAuton();
}

void staticGoalAuton(){
	//arm up
	armUp(40);
	wait1Msec(1600);
	stopAllMotorsAuton();
	mogoDownAuton();
	//move forward
	moveForwardAuton(80);
	wait1Msec(600);
	stopAllMotorsAuton();
	// waiting to stop cone from shaking
	wait1Msec(3000);
	boxForward(300);
	wait1Msec(600);
	stopAllMotorsAuton();
	openClaw(80);
	moveBackwardAuton(80);
	wait1Msec(500);
	// Done
	stopAllMotorsAuton();
}

task autonomous(){
	clearLCDLine(0);
	clearLCDLine(1);
	switch(autonomousOption) {
		case 0:
			displayLCDCenteredString(0, "RedL Mobile");
			RL_OR_BR_MobileAuton(true /* Red Left is True */);
			break;
		case 1:
			displayLCDCenteredString(0, "BlueR Mobile");
			RL_OR_BR_MobileAuton(false /* Red Left is not True */);
			break;
		case 2:
			displayLCDCenteredString(0, "Static Goal");
			staticGoalAuton();
			break;
		case 3:
			displayLCDCenteredString(0, "Disabled");
			// Disable auton, do nothing.
			break;
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task i s used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                    User Control Drivetrain functions                      */
/*                                                                           */
/*   All functions for drive train for [Digitron]Team 42627G Digital Minds   */
/*                                                                           */
/*                                                                           */
/*                                                                           */
/*---------------------------------------------------------------------------*/



/*------------------Dead zone filter------------------------*/
int filter(int input){
	if (input > 20 || input < -20){
		return input;
	}
	else {
		return 0;
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

/*------------------------Drive-----------------------------*/
task drive(){
	while (true){
		//forward backward
		int forward = filter(vexRT[Ch1]);
		//turning
		int turn = filter(vexRT[Ch3]);

		motor[driveRight] = (forward - turn);
		motor[driveLeft] = (forward + turn);
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

/*------------------Mobile Goal-----------------------------*/
task mogoLift() {
	while(true){
		//assigning lifting the mobile goal to the upper 8-pad button
		while(vexRT[Btn8U] == 1 || vexRT[Btn8UXmtr2] == 1){
			startMotor(mogo, 80);
		}
		stopMotor(mogo);
		//assigning dropping the mobile goal to the bottom 8-pad button
		while(vexRT[Btn8D] == 1 || vexRT[Btn8DXmtr2]){
			startMotor(mogo, -80);
		}
		stopMotor(mogo);
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/



/*------------------Arm and claw and boxlift-----------------------------*/

task arm() {
	while(true){
		//assigning lifting the arm to the upper 6-button pad.
		while(vexRT[Btn6U] == 1) {
			startMotor(leftArm, 80);
			startMotor(rightArm, -80);
		}
		stopMotor(leftArm);
		stopMotor(rightArm);
		//assigning dropping the arm to the bottom 6-buttom pad.
		while(vexRT[Btn6D] == 1){
			startMotor(leftArm, -80);
			startMotor(rightArm, 80);
		}
		stopMotor(leftArm);
		stopMotor(rightArm);
	}
}

task box() {
	while(true){
		//box down
		while(vexRT[Btn5U] == 1){
			startMotor(armBox, 127);
		}
		stopMotor(armBox);

		//box up
		while(vexRT[Btn5D] == 1){
			startMotor(armBox, -127);
		}
		stopMotor(armBox);
	}
}

task claw() {
	while(true){
		//claw close
		while(vexRT[Btn8R] == 1){
			startMotor(armClaw, -80);
		}
		stopMotor(armClaw);
		// claw open
		while(vexRT[Btn8L] == 1){
			startMotor(armClaw, 80);
		}
		stopMotor(armClaw);
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

//This task drives everything.Don't mess with this unless debugging.
task usercontrol() {
	startTask(drive);
	startTask(mogoLift);
	startTask(arm);
	startTask(box);
	startTask(claw);
}
