#pragma config(Motor,  port2,           driveLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armClaw,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armBox,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*               Desc: VEX 42627G Team Digital Minds Copyright               */
/*                    						Credit:																		 */
/*                    Head Developers: Mukul Rao, Jeffrey Tu				         */
/*                                    									                     */
/*                    				                                               */
/*                                                                           */
/*                                                                           */
/*     Filter Function/deadzone filter credit: Kaushik from 315 Paradigm,    */
/*                        as well as some other ideas.                       */
/*---------------------------------------------------------------------------*/

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

const short rightButton = 4;
const short centerButton = 2;
int autonomousOption = -1;

//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(true){
		if(nLCDButtons == rightButton || nLCDButtons == centerButton) {
			break;
		}
	}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

void clearAndDisplayLCD(const char* str) {
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, str);
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void pre_auton(){
	int currentOption = 0;
	// Enable LCD Display.
	bLCDBacklight = true;
	//clearing existing LCD text
	clearLCDLine(0);
	clearLCDLine(1);

	// By default disable auton.
	autonomousOption = 4;

	// Go into auton selection only if button 7R is held during boot.
	// This allows us to proceed to driver mode if Robot were to
	// get disconnected during a match.
	//if(vexRT[Btn7R] == 1){
	bool optionSelected = false;
	while(!optionSelected){
		switch(currentOption){
		case 0:
			displayLCDCenteredString(0, "Left Auton");
			displayLCDCenteredString(1, "Enter ==>");
			waitForPress();
			if(nLCDButtons == centerButton){
				waitForRelease();
				optionSelected = true;
				autonomousOption = 0;
				clearAndDisplayLCD("Left Auton");
				} else if(nLCDButtons == rightButton){
				waitForRelease();
				currentOption++;
			}
			break;
		case 1:
			displayLCDCenteredString(0, "Right Auton");
			displayLCDCenteredString(1, "Enter ==>");
			waitForPress();
			if(nLCDButtons == centerButton){
				waitForRelease();
				optionSelected = true;
				autonomousOption = 1;
				clearAndDisplayLCD("Right Auton");
				} else if(nLCDButtons == rightButton){
				waitForRelease();
				currentOption++;
			}
			break;
		case 2:
			displayLCDCenteredString(0, "Static Auton");
			displayLCDCenteredString(1, "Enter ==>");
			waitForPress();
			if(nLCDButtons == centerButton){
				waitForRelease();
				optionSelected = true;
				autonomousOption = 2;
				clearAndDisplayLCD("Static Auton");
				} else if(nLCDButtons == rightButton){
				waitForRelease();
				currentOption++;
			}
			break;
		case 3:
			displayLCDCenteredString(0, "Disable Auton");
			displayLCDCenteredString(1, "Enter ==>");
			waitForPress();
			if(nLCDButtons == centerButton){
				waitForRelease();
				optionSelected = true;
				autonomousOption = 3;
				clearAndDisplayLCD("Auton Disabled");
				} else if(nLCDButtons == rightButton){
				waitForRelease();
				currentOption = 0;
			}
			break;
		}
	}
	//} else {
	//displayLCDCenteredString(0, "Auton Disabled");
	//}

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void boxForward(int power){
	motor[armBox] = 1 * power;
}

void boxBackward(int power){
	motor[armBox] = -1 * power;
}

void openClaw(int power){
	motor[armClaw] = -1 * power;
	wait1Msec(400);
	motor[armClaw] = 0;
}

void closeClaw(int power){
	motor[armClaw] = power;
}

void armUp(int power){
	motor[leftArm] = power;
	motor[rightArm] = -1 * power;
}

void armDown(int power){
	motor[leftArm] = -1 * power;
	motor[rightArm] = power;
}

void moveForwardAuton(int power, int time){
	motor[driveLeft] = power;
	motor[driveRight] = power;
	wait1Msec(time);
	motor[driveLeft] = -25;
	motor[driveRight] = -25;
	wait1Msec(100);
	motor[driveLeft] = 0;
	motor[driveRight] = 0;
}

void moveBackwardAuton(int power, int time){
	motor[driveLeft] = -power;
	motor[driveRight] = -power;
	wait1Msec(time);
	motor[driveLeft] = -25;
	motor[driveRight] = -25;
	wait1Msec(100);
	motor[driveLeft] = 0;
	motor[driveRight] = 0;
}

void turnRightAuton(int power){
	motor[driveRight] = -power;
	motor[driveLeft] = power;
}

void turnLeftAuton(int power){
	motor[driveRight] = power;
	motor[driveLeft] = -power;
}

void stopAllMotorsAuton(){
	motor[driveRight] = 0;
	motor[driveLeft] = 0;
	motor[armBox] = 0;
	motor[armClaw] = 0;
	motor[leftArm] = 0;
	motor[mogo] = 0;
	motor[rightArm] = 0;
}

void mogoDownAuton(){
	motor[mogo] = -127;
	wait1Msec(1250);
	motor[mogo] = 0;
}

void mogoUpAuton(){
	motor[mogo] = 127;
	wait1Msec(1250);
	motor[mogo] = 0;
}

/*
void Left_OR_Right_Auton(bool left){
	// Close the claw so that cone doesn't fall off.
	closeClaw(40);
	// Lift arm
	// Bring the mogo down
	// Move forward to the mobile goal
	armUp(50);
	wait1Msec(250);
	motor[mogo] = -127;
	// mogoDown waits, no need to add additional wait here
	moveForwardAuton(127, 1675);
	motor[mogo] = 0;
	// Pickup mobile goal
	// Drop the yellow cone on mobile goal
	mogoUpAuton();
	// mogoUp waits, no need to add additional wait here
	armDown(80);
	wait1Msec(750);
	stopAllMotorsAuton();
	// Place the yellow cone on the mobile goal
	openClaw(40);
	stopAllMotorsAuton();
	//
	// Come back straight
	moveBackwardAuton(127, 1200);

	if (left) {
		turnRightAuton(80);
		} else {
		turnLeftAuton(80);
	}

	wait1Msec(650);
	stopAllMotorsAuton();
	armDown(80);
	wait1Msec(100);

	// Align the back against the fence
	moveBackwardAuton(80, 600);
	// Move forward so that there is enough clearence from the fence
	// to turn.
	moveForwardAuton(80, 225);
	if (left) {
		turnRightAuton(80);
		} else {
		turnLeftAuton(80);
	}
	wait1Msec(450);
	stopAllMotorsAuton();

	moveForwardAuton(127, 950);

	// Now turn either right or left so that the robot
	// faces the drop zone.
	if (left) {
		turnRightAuton(80);
		} else {
		turnLeftAuton(80);
	}
	wait1Msec(650);
	stopAllMotorsAuton();
	// Lift the arm up
	// Move forward so that robot's front is well within 10 point zone
	// Drop the mobile goal in 20 point zone
	// Drive back a bit
	armUp(80);
	wait1Msec(400);
	stopAllMotorsAuton();
	moveForwardAuton(127, 1250);
	mogoDownAuton();
	moveBackwardAuton(127, 150);
	mogoUpAuton();
	armDown(80);
	wait1Msec(50);
	stopAllMotorsAuton();
	moveBackwardAuton(127, 250);
} */

void Left_OR_Right_Auton(bool left){
	// Close the claw so that cone doesn't fall off.
	closeClaw(40);
	// Lift arm
	// Bring the mogo down
	// Move forward to the mobile goal
	armUp(50);
	wait1Msec(250);
	motor[mogo] = -127;
	// mogoDown waits, no need to add additional wait here
	moveForwardAuton(127, 1675);
	motor[mogo] = 0;
	// Pickup mobile goal
	// Drop the yellow cone on mobile goal
	mogoUpAuton();
	// mogoUp waits, no need to add additional wait here
	armDown(100);
	wait1Msec(750);
	stopAllMotorsAuton();
	// Place the yellow cone on the mobile goal
	openClaw(40);
	stopAllMotorsAuton();

	// Pick up and stack another cone
	if (!left) {
		// Adjust the robot for right jerk
		turnLeftAuton(80);
		wait1Msec(50);
	}
	moveForwardAuton(80, 350);
	boxForward(127);
	wait1Msec(400);
	stopAllMotorsAuton();
	openClaw(127);
	armDown(127);
	wait1Msec(300);
	stopAllMotorsAuton();
	closeClaw(127);
	armUp(80);
	wait1Msec(400);
	stopMotor(leftArm);
	stopMotor(rightArm);
	boxBackward(127);
	wait1Msec(600);
	stopMotor(armBox);
	armDown(100);
	wait1Msec(650);
	stopAllMotorsAuton();
	// Place the yellow cone on the mobile goal
	openClaw(40);
	stopAllMotorsAuton();

	//
	// Come back straight
	moveBackwardAuton(127, 1450);

	if (left) {
		turnRightAuton(80);
		} else {
		turnLeftAuton(80);
	}

	wait1Msec(875);
	stopAllMotorsAuton();

	moveForwardAuton(127, 500);

	// Now turn either right or left so that the robot
	// faces the drop zone.
	if (left) {
		turnRightAuton(80);
		} else {
		turnLeftAuton(80);
	}
	wait1Msec(700);
	stopAllMotorsAuton();
	// Lift the arm up
	// Move forward so that robot's front is well within 10 point zone
	// Drop the mobile goal in 20 point zone
	// Drive back a bit
	armUp(80);
	wait1Msec(100);
	stopAllMotorsAuton();
	moveForwardAuton(127, 1250);
	mogoDownAuton();
	moveBackwardAuton(127, 150);
	mogoUpAuton();
	armDown(127);
	wait1Msec(300);
	stopAllMotorsAuton();
	moveBackwardAuton(127, 250);

}

void staticGoalAuton(){
	//arm up
	armUp(50);
	wait1Msec(1600);
	stopAllMotorsAuton();
	//mogoDownAuton();
	//move forward
	moveForwardAuton(80, 625);
	boxForward(127);
	wait1Msec(200);
	stopAllMotorsAuton();
	// waiting to stop cone from shaking
	wait1Msec(500);
	openClaw(80);
	moveBackwardAuton(80, 500);
	boxBackward(127);
	wait1Msec(600);
	stopAllMotorsAuton();
}


task autonomous(){
	switch(autonomousOption) {
	case 0:
		clearAndDisplayLCD("Left Auton");
		Left_OR_Right_Auton(true /* Left is True */);
		break;
	case 1:
		clearAndDisplayLCD("Right Auton");
		Left_OR_Right_Auton(false /* Left is not True */);
		break;
	case 2:
		clearAndDisplayLCD("Static Auton");
		staticGoalAuton();
		break;
	case 3:
		clearAndDisplayLCD("Disabled");
		// Disable auton, do nothing.
		break;
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task i s used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                    User Control Drivetrain functions                      */
/*                                                                           */
/*   All functions for drive train for [Digitron]Team 42627G Digital Minds   */
/*                                                                           */
/*                                                                           */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// Toggle partner variable DO NOT CHANGE
int togglePartner = 1;

/*------------------Dead zone filter------------------------*/



int filter(int input){
	if (input > 20 || input < -20){
		return input;
	}
	else {
		return 0;
	}
}

task toggleTask(){
	while(true){
		if(vexRT[Btn7U] == 1){

			if(togglePartner == 1){
				togglePartner = 0;
				} else {
				togglePartner = 1;
			}

			wait1Msec(700);
		}
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

/*------------------------Drive-----------------------------*/
void driveRobot(int forward, int turn) {
	motor[driveRight] = -(forward - turn);
	motor[driveLeft] = (forward + turn);
}

task drive(){
	while (true){
		//forward backward
		int forward = togglePartner * filter(vexRT[Ch1Xmtr2]) + (1 - togglePartner) * filter(vexRT[Ch1]);
		//turning
		int turn = togglePartner * filter(vexRT[Ch3Xmtr2]) + (1 - togglePartner) * filter(vexRT[Ch3]);
		driveRobot(forward, turn);
	}
}

/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

/*------------------Mobile Goal-----------------------------*/
task mogoLift() {
	while(true){
		//assigning lifting the mobile goal to the upper 8-pad button
		while(vexRT[Btn8UXmtr2] == 1 || vexRT[Btn8U] == 1){
			startMotor(mogo, 80);
		}
		stopMotor(mogo);
		//assigning dropping the mobile goal to the bottom 8-pad button
		while(vexRT[Btn8DXmtr2] == 1 || vexRT[Btn8D] == 1){
			startMotor(mogo, -80);
		}
		stopMotor(mogo);
	}
}

/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/



/*------------------Arm and claw and boxlift-----------------------------*/

task arm() {
	while(true){
		//assigning lifting the arm to the upper 6-button pad.
		if(vexRT[Btn6U] == 1) {
			startMotor(leftArm, 80);
			startMotor(rightArm, -80);
			while(vexRT[Btn6U] == 1){}
			stopMotor(leftArm);
			stopMotor(rightArm);
		}
		//assigning dropping the arm to the bottom 6-buttom pad.
		if(vexRT[Btn6D] == 1){
			startMotor(leftArm, -80);
			startMotor(rightArm, 80);
			while (vexRT[Btn6D] == 1){}
			startMotor(leftArm, -10);
			startMotor(rightArm, 10);
		}
	}
}

//----------------------Arm Box----------------

task box() {
	while(true){
		//box down
		while(vexRT[Btn5U] == 1){
			startMotor(armBox, 127);
		}
		stopMotor(armBox);

		//box up
		while(vexRT[Btn5D] == 1){
			startMotor(armBox, -127);
		}
		stopMotor(armBox);
	}
}

task claw() {
	while(true){
		//claw open
		if(vexRT[Btn8R] == 1){
			stopMotor(armClaw);
			startMotor(armClaw, -127);
			wait1Msec(100);
			stopMotor(armClaw);
			startMotor(armClaw, -15);
		}
		// claw close
		if(vexRT[Btn8L] == 1){
			stopMotor(armClaw);
			startMotor(armClaw, 127);
			wait1Msec(300);
			stopMotor(armClaw);
			startMotor(armClaw, 15);
		}
		//abort the constant power
		if(vexRT[Btn7D] == 1 || vexRT[Btn7DXmtr2] == 1){
			stopMotor(armClaw);
		}
	}
}


/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

//This task drives everything.Don't mess with this unless debugging.
task usercontrol() {
	startTask(toggleTask);
	startTask(drive);
	startTask(mogoLift);
	startTask(arm);
	startTask(box);
	startTask(claw);
}
