#pragma config(Sensor, dgtl1,  rDriveEncoder,  sensorQuadEncoder)
#pragma config(Motor,  port2,           driveLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port4,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           TL_BR_Arm,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           TR_BL_Arm,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           roller,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armBox,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*               Desc: VEX 42627G Team Digital Minds Copyright               */
/*                    						  Credit:																	 */
/*                    Head Developers: Mukul Rao, Jeffrey Tu				         */
/*                                    									                     */
/*                    				                                               */
/*                                                                           */
/*                                                                           */
/*     Filter Function/deadzone filter credit: Kaushik from 315 Paradigm,    */
/*                        as well as some other ideas.                       */
/*---------------------------------------------------------------------------*/

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

const short RIGHT_BUTTON_LCD = 4;
const short CENTER_BUTTON_LCD = 2;
const short ZONE_20 = 20;
const short ZONE_10 = 10;
const short ZONE_5 = 5;

int autonomousOption = -1;

//Wait for Press----------------------------------------------
void waitForPress()
{
	while(true){
		if(nLCDButtons == RIGHT_BUTTON_LCD || nLCDButtons == CENTER_BUTTON_LCD) {
			break;
		}
	}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

void clearAndDisplayLCD(const char* str) {
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, str);
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void pre_auton(){
	int currentOption = 0;
	// Enable LCD Display.
	bLCDBacklight = true;
	//clearing existing LCD text
	clearLCDLine(0);
	clearLCDLine(1);

	// By default disable auton.
	autonomousOption = 4;

	// Go into auton selection only if button 7R is held during boot.
	// This allows us to proceed to driver mode if Robot were to
	// get disconnected during a match.
	if(vexRT[Btn7R] == 1){
		bool optionSelected = false;
		while(!optionSelected){
			switch(currentOption){
			case 0:
				displayLCDCenteredString(0, "20 Left");
				displayLCDCenteredString(1, "Enter ==>");
				waitForPress();
				if(nLCDButtons == CENTER_BUTTON_LCD){
					waitForRelease();
					optionSelected = true;
					autonomousOption = 0;
					clearAndDisplayLCD("20 Left");
					} else if(nLCDButtons == RIGHT_BUTTON_LCD){
					waitForRelease();
					currentOption++;
				}
				break;
			case 1:
				displayLCDCenteredString(0, "20 Right");
				displayLCDCenteredString(1, "Enter ==>");
				waitForPress();
				if(nLCDButtons == CENTER_BUTTON_LCD){
					waitForRelease();
					optionSelected = true;
					autonomousOption = 1;
					clearAndDisplayLCD("20 Right");
					} else if(nLCDButtons == RIGHT_BUTTON_LCD){
					waitForRelease();
					currentOption++;
				}
				break;
			case 2:
				displayLCDCenteredString(0, "10 Left");
				displayLCDCenteredString(1, "Enter ==>");
				waitForPress();
				if(nLCDButtons == CENTER_BUTTON_LCD){
					waitForRelease();
					optionSelected = true;
					autonomousOption = 2;
					clearAndDisplayLCD("10 Left");
					} else if(nLCDButtons == RIGHT_BUTTON_LCD){
					waitForRelease();
					currentOption++;
				}
				break;
			case 3:
				displayLCDCenteredString(0, "10 Right");
				displayLCDCenteredString(1, "Enter ==>");
				waitForPress();
				if(nLCDButtons == CENTER_BUTTON_LCD){
					waitForRelease();
					optionSelected = true;
					autonomousOption = 3;
					clearAndDisplayLCD("10 Right");
					} else if(nLCDButtons == RIGHT_BUTTON_LCD){
					waitForRelease();
					currentOption++;
				}
				break;
			case 4:
				displayLCDCenteredString(0, "5 Left");
				displayLCDCenteredString(1, "Enter ==>");
				waitForPress();
				if(nLCDButtons == CENTER_BUTTON_LCD){
					waitForRelease();
					optionSelected = true;
					autonomousOption = 4;
					clearAndDisplayLCD("5 Left");
					} else if(nLCDButtons == RIGHT_BUTTON_LCD){
					waitForRelease();
					currentOption++;
				}
				break;
			case 5:
				displayLCDCenteredString(0, "5 Right");
				displayLCDCenteredString(1, "Enter ==>");
				waitForPress();
				if(nLCDButtons == CENTER_BUTTON_LCD){
					waitForRelease();
					optionSelected = true;
					autonomousOption = 5;
					clearAndDisplayLCD("5 Right");
					} else if(nLCDButtons == RIGHT_BUTTON_LCD){
					waitForRelease();
					currentOption++;
				}
				break;
			case 6:
				displayLCDCenteredString(0, "Static Auton");
				displayLCDCenteredString(1, "Enter ==>");
				waitForPress();
				if(nLCDButtons == CENTER_BUTTON_LCD){
					waitForRelease();
					optionSelected = true;
					autonomousOption = 6;
					clearAndDisplayLCD("Static Auton");
					} else if(nLCDButtons == RIGHT_BUTTON_LCD){
					waitForRelease();
					currentOption++;
				}
				break;
			case 7:
				displayLCDCenteredString(0, "Disable Auton");
				displayLCDCenteredString(1, "Enter ==>");
				waitForPress();
				if(nLCDButtons == CENTER_BUTTON_LCD){
					waitForRelease();
					optionSelected = true;
					autonomousOption = 7;
					clearAndDisplayLCD("Auton Disabled");
					} else if(nLCDButtons == RIGHT_BUTTON_LCD){
					waitForRelease();
					currentOption = 0;
				}
				break;
			}
		}
		} else {
		displayLCDCenteredString(0, "Auton Disabled");
	}

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void boxForward(int power){
	motor[armBox] = 1 * power;
}

void boxBackward(int power){
	motor[armBox] = -1 * power;
}

void openClaw(int power){
	motor[roller] = -1 * power;
	wait1Msec(400);
	motor[roller] = -10;
}

void closeClaw(int power){
	motor[roller] = power;
}

void armUp(int power){
	motor[TL_BR_Arm] = power;
	motor[TR_BL_Arm] = -1 * power;
}

void armDown(int power){
	motor[TL_BR_Arm] = -1 * power;
	motor[TR_BL_Arm] = power;
}

void moveForwardAuton(int power, int time){
	motor[driveLeft] = power;
	motor[driveRight] = power;
	wait1Msec(time);
	motor[driveLeft] = -25;
	motor[driveRight] = -25;
	wait1Msec(100);
	motor[driveLeft] = 0;
	motor[driveRight] = 0;
}

void moveBackwardAuton(int power, int time){
	motor[driveLeft] = -power;
	motor[driveRight] = -power;
	wait1Msec(time);
	motor[driveLeft] = -25;
	motor[driveRight] = -25;
	wait1Msec(100);
	motor[driveLeft] = 0;
	motor[driveRight] = 0;
}

void turnRightAuton(int power){
	motor[driveRight] = -power;
	motor[driveLeft] = power;
}

void turnLeftAuton(int power){
	motor[driveRight] = power;
	motor[driveLeft] = -power;
}

void stopAllMotorsAuton(){
	motor[driveRight] = 0;
	motor[driveLeft] = 0;
	motor[armBox] = 0;
	motor[roller] = 0;
	motor[TL_BR_Arm] = 0;
	motor[mogo] = 0;
	motor[TR_BL_Arm] = 0;
}

void mogoDownAuton(){
	motor[mogo] = -127;
	wait1Msec(1250);
	motor[mogo] = 0;
}

void mogoUpAuton(){
	motor[mogo] = 127;
	wait1Msec(1250);
	motor[mogo] = 0;
}

void staticGoalAuton(){
	//Needs to be redone to support new robot
	//arm up
	armUp(50);
	wait1Msec(1600);
	stopAllMotorsAuton();
	//mogoDownAuton();
	//move forward
	moveForwardAuton(80, 625);
	boxForward(127);
	wait1Msec(300);
	stopAllMotorsAuton();
	// waiting to stop cone from shaking
	wait1Msec(500);
	openClaw(80);
	moveBackwardAuton(80, 500);
	boxBackward(127);
	wait1Msec(600);
	stopAllMotorsAuton();
}

void comeBackWithMogoAndTwoCones(bool left) {
	//Needs to be redone to support new robot
	// Close the claw so that cone doesn't fall off.
	closeClaw(40);
	// Lift arm
	// Bring the mogo down
	// Move forward to the mobile goal
	armUp(50);
	wait1Msec(250);
	motor[mogo] = -127;
	// mogoDown waits, no need to add additional wait here
	moveForwardAuton(127, 1675);
	motor[mogo] = 0;
	// Pickup mobile goal
	// Drop the yellow cone on mobile goal
	mogoUpAuton();
	// mogoUp waits, no need to add additional wait here
	armDown(100);
	wait1Msec(750);
	stopAllMotorsAuton();
	// Place the yellow cone on the mobile goal
	openClaw(40);
	stopAllMotorsAuton();

	/*
	if (!left) {
		// Adjust the robot for right jerk
		turnLeftAuton(80);
		wait1Msec(50);
	}
	*/

	// Pick up and stack another cone
	moveForwardAuton(80, 300);
	motor[roller] = -127;
	boxForward(127);
	wait1Msec(400);
	stopMotor(armBox);
	armDown(127);
	wait1Msec(300);
	stopAllMotorsAuton();
	closeClaw(127);
	armUp(80);
	wait1Msec(400);
	stopMotor(TL_BR_Arm);
	stopMotor(TR_BL_Arm);
	boxBackward(127);
	wait1Msec(600);
	stopMotor(armBox);
	armDown(100);
	wait1Msec(450);
	stopAllMotorsAuton();
	// Place the yellow cone on the mobile goal
	openClaw(40);
	stopAllMotorsAuton();

	//
	// Come back straight
	moveBackwardAuton(127, 1350);
}

void dropInTwentyZone(bool left) {
	//Needs to be redone to support new robot
	if (left) {
		turnLeftAuton(80);
	} else {
		turnRightAuton(80);
	}
	wait1Msec(375);

	//coming back after turning towards fence to align with 20 point zone
	stopAllMotorsAuton();

	moveBackwardAuton(127, 800);

	// Now turn either right or left so that the robot
	// faces the drop zone.
	if (left) {
		turnLeftAuton(80);
	} else {
		turnRightAuton(80);
	}
	wait1Msec(600);
	stopAllMotorsAuton();
	// Lift the arm up
	// Move forward so that robot's front is well within 10 point zone
	// Drop the mobile goal in 20 point zone
	// Drive back a bit
	armUp(80);
	wait1Msec(100);
	stopAllMotorsAuton();

	// Keep the claw open!
	motor[roller] = -40;

	//moveForwardAuton(127, 1250);
	motor[driveLeft] = 100;
	motor[driveRight] = 100;
	//wait1Msec(1250);

	mogoDownAuton();
	moveBackwardAuton(127, 150);
	mogoUpAuton();
	armDown(127);
	wait1Msec(300);
	stopAllMotorsAuton();
	moveBackwardAuton(127, 250);
}

void dropInTenZone(bool left) {
	//Needs to be redone to support new robot
	if (left) {
		turnRightAuton(100);
	} else {
		turnLeftAuton(100);
	}
	if(left){
		wait1Msec(1250);
	} else {
		wait1Msec(1200);
	}
	stopAllMotorsAuton();

	armUp(80);
	wait1Msec(100);
	stopAllMotorsAuton();
	if(left){
		moveForwardAuton(127, 500);
	} else {
		moveForwardAuton(127, 750);
	}
	// Keep the claw open!
	motor[roller] = -40;

	mogoDownAuton();
	moveBackwardAuton(127, 200);
	mogoUpAuton();
	armDown(127);
	wait1Msec(300);
	stopAllMotorsAuton();
	moveBackwardAuton(127, 400);
}

void dropInFiveZone(bool left) {
	//Needs to be redone to support new robot
	if (left) {
		turnRightAuton(80);
		} else {
		turnLeftAuton(80);
	}
	wait1Msec(1400);
	stopAllMotorsAuton();
	moveForwardAuton(80, 200);
	armUp(80);
	wait1Msec(100);
	stopAllMotorsAuton();
	// Keep the claw open!
	motor[roller] = -40;
	mogoDownAuton();
	moveBackwardAuton(127, 150);
	mogoUpAuton();
	armDown(127);
	wait1Msec(300);
	stopAllMotorsAuton();
	moveBackwardAuton(127, 200);
}

void Left_OR_Right_Auton(bool left, short zone){
	//Needs to be redone to support new robot
	comeBackWithMogoAndTwoCones(left);
	switch(zone) {
	case ZONE_20:
		dropInTwentyZone(left);
		break;
	case ZONE_10:
		dropInTenZone(left);
		break;
	case ZONE_5:
		dropInFiveZone(left);
	};
}


task autonomous(){
	//Needs to be redone to support new robot
	switch(autonomousOption) {
	case 0:
		clearAndDisplayLCD("20 Left");
		Left_OR_Right_Auton(true /* Left is True */, ZONE_20);
		break;
	case 1:
		clearAndDisplayLCD("20 Right");
		Left_OR_Right_Auton(false /* Left is not True */, ZONE_20);
		break;
	case 2:
		clearAndDisplayLCD("10 Left");
		Left_OR_Right_Auton(true /* Left is True */, ZONE_10);
		break;
	case 3:
		clearAndDisplayLCD("10 Right");
		Left_OR_Right_Auton(false /* Left is not True */, ZONE_10);
		break;
	case 4:
		clearAndDisplayLCD("5 Left");
		Left_OR_Right_Auton(true /* Left is True */, ZONE_5);
		break;
	case 5:
		clearAndDisplayLCD("5 Right");
		Left_OR_Right_Auton(false /* Left is not True */, ZONE_5);
		break;
	case 6:
		clearAndDisplayLCD("Static Auton");
		staticGoalAuton();
		break;
	case 7:
		clearAndDisplayLCD("Disabled");
		// Disable auton, do nothing.
		break;
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task i s used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                    User Control Drivetrain functions                      */
/*                                                                           */
/*   All functions for drive train for [Digitron]Team 42627G Digital Minds   */
/*                                                                           */
/*                                                                           */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// Toggle partner variable DO NOT CHANGE
int togglePartner = 1;

/*------------------Dead zone filter------------------------*/



int filter(int input){
	if (input > 20 || input < -20){
		return input;
		} else {
		return 0;
	}
}

task toggleTask(){
	while(true){
		if(vexRT[Btn7U] == 1){
			if(togglePartner == 1){
				togglePartner = 0;
				} else {
				togglePartner = 1;
			}
			wait1Msec(700);
		}
	}
}
/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

/*------------------------Drive-----------------------------*/
void driveRobot(int forward, int turn) {
	//Needs to be double checked to confirm new robot support
	motor[driveRight] = -(forward - turn);
	motor[driveLeft] = (forward + turn);
}

task drive(){
	while (true){
		//forward backward
		int forward = togglePartner * filter(vexRT[Ch1Xmtr2]) + (1 - togglePartner) * filter(vexRT[Ch1]);
		//turning
		int turn = togglePartner * filter(vexRT[Ch3Xmtr2]) + (1 - togglePartner) * filter(vexRT[Ch3]);
		driveRobot(forward, turn);
	}
}

/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

/*------------------Mobile Goal-----------------------------*/
task mogoLift() {
	while(true){
		//Needs to be double checked to confirm new robot support
		//assigning lifting the mobile goal to the upper 8-pad button
		while(vexRT[Btn8UXmtr2] == 1 || vexRT[Btn8U] == 1){
			startMotor(mogo, 80);
		}
		stopMotor(mogo);
		//assigning dropping the mobile goal to the bottom 8-pad button
		while(vexRT[Btn8DXmtr2] == 1 || vexRT[Btn8D] == 1){
			startMotor(mogo, -80);
		}
		stopMotor(mogo);
	}
}

/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/



/*------------------Arm and claw and boxlift-----------------------------*/

task arm() {
	while(true){
		//Needs to be double checked to confirm new robot support
		//assigning lifting the arm to the upper 6-button pad.
		if(vexRT[Btn6U] == 1) {
			startMotor(TL_BR_Arm, 80);
			startMotor(TR_BL_Arm, -80);
			while(vexRT[Btn6U] == 1){}
			stopMotor(TL_BR_Arm);
			stopMotor(TR_BL_Arm);
		}
		//assigning dropping the arm to the bottom 6-buttom pad.
		if(vexRT[Btn6D] == 1){
			startMotor(TL_BR_Arm, -80);
			startMotor(TR_BL_Arm, 80);
			while (vexRT[Btn6D] == 1){}
			startMotor(TL_BR_Arm, -10);
			startMotor(TR_BL_Arm, 10);
		}
	}
}

//----------------------Arm Box----------------

task box() {
	while(true){
		//Needs to be double checked to confirm new robot support
		//box down
		while(vexRT[Btn5U] == 1){
			startMotor(armBox, 127);
		}
		stopMotor(armBox);

		//box up
		while(vexRT[Btn5D] == 1){
			startMotor(armBox, -127);
		}
		stopMotor(armBox);
	}
}

task claw() {
	//Needs to be redone (Brand new intake design) Start from scratch
	while(true){
		//roller intake
		if(vexRT[Btn8R] == 1){
			stopMotor(roller);
			startMotor(roller, -127);
			wait1Msec(1500);
			stopMotor(roller);
			startMotor(roller, -10);
		}
		// roller release
		if(vexRT[Btn8L] == 1){
			stopMotor(roller);
			startMotor(roller, 127);
			wait1Msec(1500);
			stopMotor(roller);
			startMotor(roller, 10);
		}
		//abort the constant power
		if(vexRT[Btn7D] == 1 || vexRT[Btn7DXmtr2] == 1){
			stopMotor(roller);
		}
	}
}


/*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_*/

//This task drives everything.Don't mess with this unless debugging. Double check all function support with new robot.
task usercontrol() {
	startTask(toggleTask);
	startTask(drive);
	startTask(mogoLift);
	startTask(arm);
	startTask(box);
	startTask(claw);
}
